const PLATFORMS = window.workspace.platforms;
let currentPage = "dashboard";
let browserVisible = false;
let modalBrowserVisible = false;
let appState = { accounts:[], settings:{theme:'light'}, activeAccount:null };
let selectedPlatform = null;
const $ = id => document.getElementById(id);
function esc(value) { return String(value ?? '').replace(/[&<>"']/g, c => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[c])); }
function toast(message) { const el=$('toast'); el.textContent=message; el.classList.add('show'); clearTimeout(toast.timer); toast.timer=setTimeout(()=>el.classList.remove('show'),3000); }
function relativeTime(date) { if (!date) return 'Never opened'; const d=new Date(date), diff=Date.now()-d.getTime(), min=Math.floor(diff/60000); if(min<1)return 'Just now'; if(min<60)return `${min} minute${min===1?'':'s'} ago`; const today=new Date().toDateString()===d.toDateString(); if(today)return `Today ${d.toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}`; const yesterday=new Date(Date.now()-86400000).toDateString()===d.toDateString(); if(yesterday)return 'Yesterday'; return d.toLocaleDateString([], {month:'short',day:'numeric',year:'numeric'}); }
function renderNav() {
  const platformButtons=Object.entries(PLATFORMS).map(([id,p])=>`<button class="nav-item ${selectedPlatform===id?'active':''}" data-platform="${id}"><span class="nav-icon" style="--platform-color:${p.color}">${p.glyph}</span>${p.name}<span class="nav-count">${appState.accounts.filter(a=>a.platform===id).length||''}</span></button>`).join('');
  const accounts=selectedPlatform?appState.accounts.filter(a=>a.platform===selectedPlatform):[];
  const accountList=selectedPlatform&&accounts.length?`<div class="sidebar-accounts"><div class="side-label account-label">ACCOUNTS</div>${accounts.map(a=>`<button class="sidebar-account ${appState.activeAccount===a.id?'selected':''}" data-open="${a.id}"><span class="mini-avatar" style="--avatar-bg:${PLATFORMS[a.platform].color}">${esc(a.name.trim()[0]?.toUpperCase()||'?')}</span><span class="sidebar-account-name">${esc(a.name)}</span></button>`).join('')}</div>`:'';
  $('platform-nav').innerHTML=platformButtons+accountList;
  document.querySelectorAll('[data-platform]').forEach(b=>b.onclick=()=>{navigatePlatform(b.dataset.platform);});
  document.querySelectorAll('.sidebar-account[data-open]').forEach(b=>b.onclick=()=>call('openAccount',b.dataset.open));
}
function render() { renderNav(); if(window.renderWorkspaceNav) renderWorkspaceNav(); document.body.classList.toggle('dark', appState.settings.theme==='dark'); if(window.syncModeControl)syncModeControl(); if(selectedPlatform) renderPlatform(); else if(currentPage==='settings') renderSettings(); else if(window.renderWorkspacePage) renderWorkspacePage(currentPage); else renderHome(); }
function renderHome() {
  $('page-title').textContent='Social Workspace'; $('back-home').classList.add('hidden'); $('browser-toolbar').classList.add('hidden');
  $('content').innerHTML=`<div class="home-intro"><div><div class="eyebrow">YOUR PLATFORMS</div><h2>All your accounts, one workspace</h2><p>Choose a platform to view its accounts or add a new login session.</p></div><button class="primary" id="intro-add">＋ Add Account</button></div><div class="platform-grid">${Object.entries(PLATFORMS).map(([id,p])=>{const count=appState.accounts.filter(a=>a.platform===id).length;return `<button class="platform-card" data-platform="${id}"><span class="platform-large-icon" style="--platform-color:${p.color}">${p.glyph}</span><span><strong>${p.name}</strong><small>${count} account${count===1?'':'s'}</small></span><span class="chevron">→</span></button>`}).join('')}</div>`;
  $('intro-add').onclick=showAdd; document.querySelectorAll('.platform-card').forEach(b=>b.onclick=()=>{navigatePlatform(b.dataset.platform);});
}
function renderPlatform() {
  const p=PLATFORMS[selectedPlatform], accounts=appState.accounts.filter(a=>a.platform===selectedPlatform), active=appState.accounts.find(a=>a.id===appState.activeAccount);
  $('page-title').textContent=p.name; $('back-home').classList.remove('hidden'); $('browser-toolbar').classList.toggle('hidden', !(browserVisible&&active&&active.platform===selectedPlatform)); $('messenger-btn').classList.toggle('hidden', selectedPlatform!=='facebook');
  $('content').innerHTML=`<div class="section-head"><h2>${p.name} accounts <span class="count">${accounts.length}</span></h2><button class="primary" id="platform-add">＋ Add Account</button></div>${accounts.length?`<div class="account-grid">${accounts.map(a=>`<article class="card account-card"><div class="account-main"><div class="avatar" style="--avatar-bg:${p.color}">${esc(a.name.trim()[0]?.toUpperCase()||'?')}</div><div><div class="account-name">${esc(a.name)}</div><div class="platform-name">${p.name}${a.id===appState.activeAccount?' · Open':' · Session saved'}</div></div></div><div class="last-opened">Last opened: ${relativeTime(a.lastOpenedAt)}<br><span title="Login is managed by the platform; session presence does not confirm authentication.">Login status: verify on platform</span></div><div class="card-actions"><button class="open" data-open="${a.id}">Open</button><button data-rename="${a.id}">Rename</button><button class="delete" data-delete="${a.id}">Delete</button></div></article>`).join('')}</div>`:'<div class="card" style="text-align:center;padding:55px;color:var(--muted)">No accounts here yet.<br><button class="primary" id="empty-add" style="margin-top:18px">＋ Add Account</button></div>'}`;
  if(selectedPlatform==='whatsapp')renderWhatsAppFallback(); if(selectedPlatform==='gmail')renderGmailSetup(); if(selectedPlatform==='facebook'||selectedPlatform==='instagram')renderMetaSetup(selectedPlatform); $('platform-add')?.addEventListener('click',showAdd); $('empty-add')?.addEventListener('click',showAdd); document.querySelectorAll('[data-open]').forEach(b=>b.onclick=()=>call('openAccount',b.dataset.open)); document.querySelectorAll('[data-rename]').forEach(b=>b.onclick=()=>showRename(b.dataset.rename)); document.querySelectorAll('[data-delete]').forEach(b=>b.onclick=()=>showDelete(b.dataset.delete));
}
function showModal(html, bind) { modalBrowserVisible=browserVisible; window.workspace.setBrowserVisible(false); $('modal').innerHTML=html; $('modal-backdrop').classList.remove('hidden'); bind(); }
function closeModal() { $('modal-backdrop').classList.add('hidden'); window.workspace.setBrowserVisible(modalBrowserVisible); }
function showAdd() { showModal(`<h2>Add account</h2><div class="form-field"><label>Platform</label><select class="select" id="modal-platform">${Object.entries(PLATFORMS).map(([id,p])=>`<option value="${id}" ${id===selectedPlatform?'selected':''}>${p.name}</option>`).join('')}</select></div><div class="form-field"><label>Account name</label><input class="text-input" id="modal-name" placeholder="e.g. Main Account" autofocus></div><p style="color:var(--muted);font-size:12px">The official platform home page will open. Login is always manual and passwords are never stored.</p><div class="modal-footer"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="submit">Add Account</button></div>`,()=>{ $('cancel').onclick=closeModal; $('submit').onclick=async()=>{const name=$('modal-name').value.trim(); if(!name)return toast('Enter an account name.'); selectedPlatform=$('modal-platform').value; closeModal(); await call('createAccount',selectedPlatform,name);}; }); }
function showRename(id) { const a=appState.accounts.find(x=>x.id===id); showModal(`<h2>Rename account</h2><div class="form-field"><label>Account name</label><input class="text-input" id="rename-name" value="${esc(a.name)}"></div><div class="modal-footer"><button class="secondary" id="cancel">Cancel</button><button class="primary" id="submit">Save name</button></div>`,()=>{ $('cancel').onclick=closeModal; $('submit').onclick=async()=>{const name=$('rename-name').value.trim(); if(!name)return toast('Enter an account name.'); closeModal(); await call('renameAccount',id,name);}; }); }
function showDelete(id) { const a=appState.accounts.find(x=>x.id===id); const confirmDelete=appState.settings.confirmDelete!==false; const remove=async()=>{closeModal(); await call('deleteAccount',id);}; if(!confirmDelete){remove();return;} showModal(`<h2>Delete “${esc(a.name)}”?</h2><p style="color:var(--muted);line-height:1.6">This removes the account from the workspace and clears its local Electron session data.</p><div class="modal-footer"><button class="secondary" id="cancel">Cancel</button><button class="danger" id="submit">Delete</button></div>`,()=>{$('cancel').onclick=closeModal;$('submit').onclick=remove;}); }
function renderSettings() { currentPage='settings'; selectedPlatform=null; document.body.classList.toggle('dark',appState.settings.theme==='dark'); renderNav(); $('page-title').textContent='Settings'; $('back-home').classList.add('hidden'); $('browser-toolbar').classList.add('hidden'); $('content').innerHTML=`<div class="settings-grid"><div class="card"><div class="settings-row"><div><strong>Appearance</strong><p>Choose the workspace color theme.</p></div><select class="select" id="theme"><option value="light">Light mode</option><option value="dark">Dark mode</option></select></div><hr><div class="settings-row"><div><strong>Startup</strong><p>What opens when the app starts.</p></div><select class="select" id="startup"><option value="dashboard">Open dashboard</option><option value="last">Open last used account</option></select></div></div><div class="card"><div class="settings-row"><div><strong>Account preferences</strong><p>Control confirmations and account memory.</p></div></div><hr><div class="settings-row"><span>Confirm before delete</span><label class="switch"><input type="checkbox" id="confirm-delete"><span></span></label></div><div class="settings-row"><span>Remember last opened account</span><label class="switch"><input type="checkbox" id="remember-last"><span></span></label></div></div><div class="card"><div class="settings-row"><div><strong>Account metadata</strong><p>Exports never contain passwords or cookies.</p></div><div><button class="secondary" id="export">Export</button> <button class="secondary" id="import">Import</button></div></div></div><div class="card"><div class="settings-row"><div><strong>Session data</strong><p>Clearing a session signs that account out of this application.</p></div><div><button class="secondary" id="clear-selected">Clear selected</button> <button class="danger" id="clear-all">Clear all</button></div></div></div></div>`; $('theme').value=appState.settings.theme||'light'; $('startup').value=appState.settings.startup||'dashboard'; $('confirm-delete').checked=appState.settings.confirmDelete!==false; $('remember-last').checked=appState.settings.rememberLast!==false; $('theme').onchange=saveSettings; $('startup').onchange=saveSettings; $('confirm-delete').onchange=saveSettings; $('remember-last').onchange=saveSettings; $('export').onclick=()=>call('exportAccounts'); $('import').onclick=()=>call('importAccounts'); $('clear-selected').onclick=()=>{if(appState.activeAccount)call('clearSession',appState.activeAccount);else toast('Open an account first.')}; $('clear-all').onclick=()=>{if(confirm('Clear every local account session? This will sign all accounts out from this application.'))call('clearAllSessions');}; }
async function saveSettings(){await window.workspace.setSettings({theme:$('theme').value,startup:$('startup').value,confirmDelete:$('confirm-delete').checked,rememberLast:$('remember-last').checked}); appState.settings=await window.workspace.getState().then(s=>s.settings); renderSettings(); toast('Settings saved.');}
async function call(action,...args) { try { if(action==='openAccount'||action==='createAccount'){ browserVisible=true; toast('Opening account…'); } const response=await window.workspace[action](...args); if(response?.ok===false){ appState=await window.workspace.getState(); render(); return; } const s=await window.workspace.getState(); appState=s; if(s.externalFallback)browserVisible=false; if(action==='openAccount'||action==='createAccount'||action==='openOriginalConversation'){selectedPlatform=s.accounts.find(a=>a.id===s.activeAccount)?.platform||selectedPlatform;} render(); if(action==='createAccount'||action==='openAccount')toast(s.externalFallback?'Embedded WhatsApp unavailable. Use Open WhatsApp in External Browser to continue.':s.browserError||'Account opened.'); else if(action==='deleteAccount')toast('Account deleted and session cleared.'); else if(action==='renameAccount')toast('Account renamed.'); } catch(error){toast(error.message||'This action could not be completed.');} }
document.querySelectorAll('[data-browser]').forEach(b=>b.onclick=()=>call('browserAction',b.dataset.browser)); $('back-home').onclick=async()=>{await window.workspace.goHome();appState=await window.workspace.getState();selectedPlatform=null;currentPage='dashboard';browserVisible=false;render();}; $('add-account-side').onclick=showAdd; $('add-account-top').onclick=showAdd; $('settings-side').onclick=()=>navigatePage('settings'); $('theme-toggle').onclick=async()=>{await window.workspace.setSettings({theme:appState.settings.theme==='dark'?'light':'dark'}); appState=(await window.workspace.getState()); render();}; $('modal-backdrop').onclick=e=>{if(e.target.id==='modal-backdrop')closeModal();}; window.workspace.onError(toast); window.workspace.onBrowserState(s=>{ $('current-url').textContent=s.url||''; document.querySelector('[data-browser=back]').disabled=!s.canGoBack; document.querySelector('[data-browser=forward]').disabled=!s.canGoForward; if(!appState.activeAccount||appState.activeAccount!==s.accountId){browserVisible=true; appState.activeAccount=s.accountId; const account=appState.accounts.find(a=>a.id===s.accountId); if(account){selectedPlatform=account.platform; render();}} }); window.addEventListener('DOMContentLoaded',async()=>{appState=await window.workspace.getState(); selectedPlatform=null; render();});
async function navigatePlatform(id) { await window.workspace.setBrowserVisible(false); browserVisible=false; selectedPlatform=id; currentPage='platform'; render(); }
async function navigatePage(page) { await window.workspace.setBrowserVisible(false); browserVisible=false; selectedPlatform=null; currentPage=page; render(); }
window.workspace.onStateChanged(state=>{ appState=state; });
document.addEventListener('keydown',event=>{if(event.key==='Escape'&&!$('modal-backdrop').classList.contains('hidden'))closeModal();});

function renderWhatsAppFallback(){
  $('browser-toolbar').classList.add('hidden');
  $('content').insertAdjacentHTML('afterbegin','<section class="card whatsapp-fallback" role="status"><h3>Embedded WhatsApp unavailable</h3><p>This workspace currently uses the external-browser fallback because embedded WhatsApp is not reliably available. Choose “Open WhatsApp in External Browser” on your account card to continue.</p><p class="muted">Your saved account and session partition stay unchanged. The external browser has its own login; opening it does not verify or sign in this Electron account.</p></section>');
  document.querySelectorAll('.account-card [data-open]').forEach(button=>{
    const card=button.closest('.account-card');
    card.querySelector('.platform-name').textContent='WhatsApp';
    // Availability and authentication are separate. This build intentionally keeps
    // the existing external-only policy; it has no verified Embedded Available state.
    card.querySelector('.last-opened').textContent=`Last opened in workspace: ${relativeTime(appState.accounts.find(a=>a.id===button.dataset.open)?.lastOpenedAt)}`;
    card.querySelector('.card-actions').insertAdjacentHTML('beforebegin','<dl class="whatsapp-status" aria-label="WhatsApp account status"><div><dt>Embedded access</dt><dd><span class="badge">Embedded Unavailable</span></dd></div><div><dt>Access method</dt><dd><span class="badge">External Browser Only</span></dd></div><div><dt>Electron login</dt><dd><span class="badge">Login Verification Required</span></dd></div></dl>');
    button.title='Show embedded availability and external-browser options';
    const external=document.createElement('button');external.className='secondary whatsapp-external';external.textContent='Open WhatsApp in External Browser';
    external.onclick=async()=>{
      external.disabled=true;
      try{const response=await window.workspace.openWhatsAppExternal(button.dataset.open);if(response.ok)toast('Browser opened. Electron login is still unverified.');else toast(response.error||'Could not open the external browser. Please try again.');}
      catch{toast('Could not open the external browser. Please try again.');}
      finally{external.disabled=false;}
    };
    card.append(external);
  });
}
