/* Workspace screens extend the original account renderer and preload bridge. */
const workspaceMode = new WorkspaceMode.Mode(window.localStorage);
const demoStore = new WorkspaceData.Store(window.localStorage);
const messagingProvider = new WorkspaceData.MockMessagingProvider();
const aiProvider = new WorkspaceData.MockAIProvider();
const realLeadProvider = new WorkspaceData.LocalLeadProvider();
const publishingProvider = new WorkspaceData.MockPublishingProvider();
const PAGE_NAMES = {dashboard:'Dashboard',inbox:'Unified Inbox',leads:'AI Leads',composer:'Create Post',scheduler:'Scheduler',calendar:'Content Calendar',analytics:'Analytics Overview',reports:'Reports',listening:'Social Listening'};
let inboxFilter={search:'',platform:'',account:'',state:'active'};
let selectedConversation=demoStore.data.messages[0]?.id;
let leadFilter='All Leads';
let composer={text:'',accountIds:[],media:[],status:'draft',scheduledAt:''};
let calendarDate=new Date();
let calendarMode='month';
const demoBanner=()=>`<div class="demo-notice"><span class="badge">DEMO WORKSPACE</span> Messages, AI classifications and publishing are simulated. Account sessions are real; official integrations are pending.</div>${demoStore.warning?`<p role="alert">${esc(demoStore.warning)}</p>`:''}`;
const empty=(title,detail)=>`<div class="empty-state"><div class="empty-icon">◇</div><h3>${esc(title)}</h3><p>${esc(detail)}</p></div>`;
const dateLabel=value=>value?new Date(value).toLocaleString([], {month:'short',day:'numeric',hour:'numeric',minute:'2-digit'}):'Not scheduled';
const badge=value=>`<span class="badge ${['HOT_LEAD','scheduled','New'].includes(value)?'accent':''}">${esc(value.replaceAll('_',' '))}</span>`;
const platformIcon=id=>`<span class="platform-dot" style="--platform-color:${PLATFORMS[id]?.color||'#748096'}" title="${esc(PLATFORMS[id]?.name||id)}">${esc(PLATFORMS[id]?.glyph||'?')}</span>`;
const options=(items,value)=>items.map(([id,label])=>`<option value="${esc(id)}" ${id===value?'selected':''}>${esc(label)}</option>`).join('');
function safely(fn){return async(...args)=>{try{await fn(...args);}catch(error){toast(error.message||'This action is temporarily unavailable.');}};}
function renderWorkspaceNav(){
  const groups=[['',[['dashboard','◫']]],['INBOX',[['inbox','▤'],['leads','✧']]],['PUBLISH',[['composer','＋'],['scheduler','◷'],['calendar','▦']]],['ANALYTICS',[['analytics','◴'],['reports','▥'],['listening','⌁']]]];
  $('workspace-nav').innerHTML=groups.map(([label,items])=>`${label?`<div class="side-label">${label}</div>`:''}${items.map(([id,icon])=>`<button class="nav-item ${!selectedPlatform&&currentPage===id?'active':''}" data-page="${id}" ${currentPage===id?'aria-current="page"':''}><span class="nav-icon">${icon}</span>${PAGE_NAMES[id]}</button>`).join('')}`).join('');
  $('workspace-nav').querySelectorAll('[data-page]').forEach(b=>b.onclick=()=>navigatePage(b.dataset.page));
}
function pageHeader(title,description,action=''){return `<div class="section-head"><div><h2>${title}</h2><p class="muted">${description}</p></div>${action}</div>`;}
function renderWorkspacePage(page){
  $('page-title').textContent=PAGE_NAMES[page]||'Dashboard';
  $('back-home').classList.add('hidden');$('browser-toolbar').classList.add('hidden');
  const screens={dashboard:renderDashboard,inbox:renderInbox,leads:renderLeads,composer:renderComposer,scheduler:renderScheduler,calendar:renderCalendar,analytics:renderAnalytics,reports:renderReports,listening:renderListening};
  try{if(!workspaceMode.demo&&page!=='inbox'){renderRealPage(page);return;}(screens[page]||renderDashboard)();}catch(error){$('content').innerHTML=empty('This page could not load',error.message);}
}
function stats(){
  const m=WorkspaceData.metrics(demoStore.data);
  return `<div class="metric-grid">${[['Available platforms',Object.keys(PLATFORMS).length,'Real registry'],['Saved accounts',appState.accounts.length,'Check login on platform'],['Unread messages',m.unread,'Demo'],['Potential leads',m.leads,'Demo AI classification'],['Scheduled posts',m.scheduled,'Local demo queue'],['Posts published',m.published,'Simulations only']].map(([label,note,source])=>`<div class="card metric"><span>${label}</span><strong>${note}</strong><small>${source}</small></div>`).join('')}</div>`;
}
function distribution(){return Object.entries(PLATFORMS).map(([id,p])=>{const count=appState.accounts.filter(a=>a.platform===id).length;return `<div class="distribution-row">${platformIcon(id)}<span>${p.name}</span><meter min="0" max="${Math.max(1,appState.accounts.length)}" value="${count}">${count}</meter><strong>${count}</strong></div>`;}).join('');}
function postAccounts(p){return p.accountIds.map(id=>{const a=appState.accounts.find(a=>a.id===id);return a?`${PLATFORMS[a.platform]?.name} · ${a.name}`:'Removed account';}).join(', ')||'No accounts selected';}
function renderDashboard(){
  const m=WorkspaceData.metrics(demoStore.data), upcoming=demoStore.data.posts.filter(p=>p.status==='scheduled').sort((a,b)=>a.scheduledAt.localeCompare(b.scheduledAt)).slice(0,3);
  $('content').innerHTML=pageHeader('Your workspace, at a glance','Manage your accounts and plan what comes next.','<button class="primary" id="dashboard-create">＋ Create post</button>')+demoBanner()+stats()+`<div class="overview-grid"><section class="card"><h3>Recent messages <span class="muted">· Demo</span></h3>${demoStore.data.messages.slice(0,3).map(m=>`<button class="message-summary" data-conversation="${m.id}">${platformIcon(m.platform)}${badge('Demo')}<span><strong>${esc(m.senderName)}</strong><small>${esc(m.message)}</small></span><span class="muted">→</span></button>`).join('')}<button class="text-button" id="dashboard-inbox">View unified inbox →</button></section><section class="card"><h3>Upcoming scheduled content</h3>${upcoming.length?upcoming.map(p=>`<div class="simple-row"><strong>${esc(p.text.slice(0,80))}</strong><small>${esc(postAccounts(p))} · ${dateLabel(p.scheduledAt)}</small>${badge('Demo')}${badge('scheduled')}</div>`).join(''):empty('Your queue is clear','Save a scheduled demo post to see it here.')}</section><section class="card"><h3>Account status</h3>${appState.accounts.length?appState.accounts.slice(0,5).map(a=>`<button class="message-summary" data-account-platform="${esc(a.platform)}">${platformIcon(a.platform)}<span><strong>${esc(a.name)}</strong><small>Session saved · Last opened ${relativeTime(a.lastOpenedAt)}</small></span></button>`).join(''):empty('Add your first account','Each account keeps a separate persistent session.')}<p class="muted">Session storage does not confirm whether a platform login is still valid.</p></section><section class="card"><h3>Platform distribution <span class="muted">· Real accounts</span></h3>${distribution()}</section><section class="card"><h3>Recent activity</h3>${demoStore.data.activity.slice(0,4).map(a=>`<div class="simple-row">${esc(a.text)}<small>${dateLabel(a.timestamp)} · Demo</small></div>`).join('')||'<p class="muted">No demo publishing activity yet.</p>'}</section><section class="card"><h3>AI lead focus</h3><div class="focus-count">${m.leads}</div><p class="muted">Demo conversations with potential business intent. Review the classification before taking action.</p><button class="secondary" id="dashboard-leads">Review AI leads →</button></section></div><h3 class="section-title">Your platforms</h3><div id="dashboard-platforms" class="platform-grid">${Object.entries(PLATFORMS).map(([id,p])=>`<button class="platform-card" data-account-platform="${id}">${platformIcon(id)}<span><strong>${p.name}</strong><small>${appState.accounts.filter(a=>a.platform===id).length} accounts</small></span><span class="chevron">→</span></button>`).join('')}</div>`;
  $('dashboard-create').onclick=()=>navigatePage('composer');$('dashboard-inbox').onclick=()=>navigatePage('inbox');$('dashboard-leads').onclick=()=>navigatePage('leads');
  document.querySelectorAll('[data-conversation]').forEach(b=>b.onclick=()=>{selectedConversation=b.dataset.conversation;navigatePage('inbox');});
  document.querySelectorAll('[data-account-platform]').forEach(b=>b.onclick=()=>navigatePlatform(b.dataset.accountPlatform));
}
function renderLeads(){
  const filters=['All Leads','Hot Leads','Potential Leads','Follow-up','Replied','Archived'];
  const leads=demoStore.data.messages.filter(m=>{const c=m.classification.category;if(leadFilter==='Archived')return m.leadStatus==='Archived';if(m.leadStatus==='Archived')return false;if(leadFilter==='Follow-up')return m.followUp;if(leadFilter==='Replied')return m.leadStatus==='Replied';return leadFilter==='Hot Leads'?c==='HOT_LEAD':leadFilter==='Potential Leads'?c==='POTENTIAL_LEAD':['HOT_LEAD','POTENTIAL_LEAD','EXISTING_CLIENT'].includes(c);});
  $('content').innerHTML=pageHeader('Focus on conversations that matter','Review buying intent, choose a next step, and keep track of follow-ups.')+demoBanner()+`<div class="tabs">${filters.map(f=>`<button class="${leadFilter===f?'active':''}" data-lead-filter="${f}">${f}</button>`).join('')}</div><div class="lead-grid">${leads.map(m=>`<article class="card lead-card"><span class="badge demo-record">Demo</span><div class="section-head"><div class="conversation-heading">${platformIcon(m.platform)}<strong>${esc(m.senderName)}</strong></div><div class="lead-score" title="Mock lead score out of 100">${m.classification.score}<small>/100</small></div></div><small class="muted">${esc(m.accountName)} · ${dateLabel(m.timestamp)}</small><p class="lead-message">“${esc(m.message)}”</p><div class="action-row">${badge(m.classification.category)}${badge(m.leadStatus)}</div><p><strong>${esc(m.classification.service)}</strong></p><p class="muted">${esc(m.classification.summary)}</p><details><summary>Suggested reply · Mock AI</summary><p class="suggested-reply">${esc(m.classification.suggestedReply)}</p><button class="secondary" data-copy-reply="${m.id}">Copy suggestion</button></details><div class="lead-controls"><label>Status<select class="select" data-lead-status="${m.id}">${options(['New','Contacted','Replied','Won','Archived'].map(x=>[x,x]),m.leadStatus)}</select></label><label class="check-label"><input type="checkbox" data-follow-up="${m.id}" ${m.followUp?'checked':''}> Follow-up</label></div><button class="text-button" data-lead-open="${m.id}">View conversation →</button></article>`).join('')||empty('No leads in this view','Choose another filter to review demo classifications.')}</div><p class="integration-note">Classification provider: MockAIProvider. General, irrelevant and spam messages remain in Unified Inbox. Nothing is sent automatically.</p>`;
  document.querySelectorAll('[data-lead-filter]').forEach(b=>b.onclick=()=>{leadFilter=b.dataset.leadFilter;renderLeads();});
  document.querySelectorAll('[data-lead-status]').forEach(b=>b.onchange=safely(()=>{demoStore.updateMessage(b.dataset.leadStatus,{leadStatus:b.value});renderLeads();}));
  document.querySelectorAll('[data-follow-up]').forEach(b=>b.onchange=safely(()=>{demoStore.updateMessage(b.dataset.followUp,{followUp:b.checked});renderLeads();}));
  document.querySelectorAll('[data-lead-open]').forEach(b=>b.onclick=()=>{selectedConversation=b.dataset.leadOpen;inboxFilter={search:'',platform:'',account:'',state:'all'};navigatePage('inbox');});
  document.querySelectorAll('[data-copy-reply]').forEach(b=>b.onclick=safely(async()=>{const result=await aiProvider.classify(demoStore.data.messages.find(m=>m.id===b.dataset.copyReply));await navigator.clipboard.writeText(result.suggestedReply);toast('Suggested reply copied.');}));
}
function localDateTime(iso){if(!iso)return '';const d=new Date(iso);return new Date(d.getTime()-d.getTimezoneOffset()*60000).toISOString().slice(0,16);}
function renderComposer(){
  $('content').innerHTML=pageHeader(composer.id?'Edit post':'Create something worth sharing','Choose individual accounts, write your post, and preview it before saving.')+demoBanner()+`<div class="composer-layout"><section class="card"><h3>Publish to</h3><div class="account-picker">${Object.entries(PLATFORMS).map(([id,p])=>{const accounts=appState.accounts.filter(a=>a.platform===id);return accounts.length?`<fieldset><legend>${platformIcon(id)} ${p.name}</legend>${accounts.map(a=>`<label class="account-choice"><input type="checkbox" data-post-account="${esc(a.id)}" ${composer.accountIds.includes(a.id)?'checked':''}>${esc(a.name)}</label>`).join('')}</fieldset>`:'';}).join('')||'<p class="muted">Add an account using “Add Account” above to select a publishing destination. You can save a draft without one.</p>'}</div><label class="field-label" for="post-text">Post content</label><textarea id="post-text" class="text-input" rows="7" placeholder="What would you like to share?">${esc(composer.text)}</textarea><div class="composer-meta"><span id="char-count">${composer.text.length} characters</span><span>Platform-specific limits pending</span></div><label class="media-upload" for="post-media">＋ Attach images <small>PNG, JPEG or WebP · up to 3 images, 1 MB each · stored locally</small></label><input id="post-media" type="file" accept="image/png,image/jpeg,image/webp" multiple class="full-width"><div id="media-list"></div><label class="field-label" for="post-date">Schedule date and time (${esc(Intl.DateTimeFormat().resolvedOptions().timeZone)})</label><input id="post-date" type="datetime-local" class="text-input" value="${localDateTime(composer.scheduledAt)}"><div class="action-row composer-actions"><button id="save-draft" class="secondary">Save draft</button><button id="schedule-post" class="secondary">Schedule demo</button><button id="publish-post" class="primary">Publish now · Demo</button></div><p class="integration-note">Publishing is simulated. Scheduled posts remain in the local planning queue; they are never sent automatically.</p></section><aside class="card preview-panel"><div class="section-head"><h3>Post preview</h3>${badge('demo')}</div><div class="preview-account"><div class="avatar">SW</div><div><strong>Social Workspace</strong><small id="preview-accounts"></small></div></div><p id="post-preview" class="post-preview"></p><div id="preview-media" class="preview-media"></div><hr><p class="muted">Generic preview. Final formatting will depend on the selected platform.</p></aside></div>`;
  $('post-text').oninput=e=>{composer.text=e.target.value;updatePreview();};
  $('post-date').onchange=e=>{composer.scheduledAt=e.target.value?new Date(e.target.value).toISOString():'';};
  document.querySelectorAll('[data-post-account]').forEach(b=>b.onchange=()=>{composer.accountIds=Array.from(document.querySelectorAll('[data-post-account]:checked')).map(b=>b.dataset.postAccount);updatePreview();});
  $('post-media').onchange=safely(async e=>{const files=Array.from(e.target.files);if(files.length+composer.media.length>3)throw new Error('Choose up to three images.');if(files.some(f=>f.size>1024*1024||!['image/png','image/jpeg','image/webp'].includes(f.type)))throw new Error('Use PNG, JPEG or WebP images up to 1 MB each.');const media=await Promise.all(files.map(file=>new Promise((resolve,reject)=>{const reader=new FileReader();reader.onload=()=>resolve({name:file.name,type:file.type,data:reader.result});reader.onerror=()=>reject(new Error('Could not read this image.'));reader.readAsDataURL(file);})));composer.media.push(...media);e.target.value='';updatePreview();});
  $('save-draft').onclick=safely(()=>saveComposer('draft'));$('schedule-post').onclick=safely(()=>saveComposer('scheduled'));$('publish-post').onclick=safely(()=>saveComposer('simulated'));updatePreview();
}
function updatePreview(){
  $('post-preview').textContent=composer.text||'Your post preview will appear here…';$('char-count').textContent=`${composer.text.length} characters`;$('preview-accounts').textContent=postAccounts(composer);
  $('media-list').innerHTML=composer.media.map((m,i)=>`<div class="simple-row">${esc(m.name)} <button class="text-button" data-remove-media="${i}" aria-label="Remove ${esc(m.name)}">Remove</button></div>`).join('');
  $('preview-media').innerHTML=composer.media.filter(m=>/^data:image\/(png|jpeg|webp);base64,/.test(m.data)).map(m=>`<img src="${esc(m.data)}" alt="${esc(m.name)}">`).join('');
  document.querySelectorAll('[data-remove-media]').forEach(b=>b.onclick=()=>{composer.media.splice(Number(b.dataset.removeMedia),1);updatePreview();});
}
async function saveComposer(status){
  if(!workspaceMode.demo)throw new Error('Demo Mode is off. No real publishing connector is configured.');
  let post={...composer,status};if(status==='simulated')post=await publishingProvider.publish(post);
  demoStore.savePost(post,appState.accounts);composer={text:'',accountIds:[],media:[],status:'draft',scheduledAt:''};toast(status==='simulated'?'Publish simulated. Nothing was sent.':status==='scheduled'?'Demo post scheduled locally.':'Draft saved.');await navigatePage('scheduler');
}
function renderScheduler(){
  const posts=[...demoStore.data.posts].sort((a,b)=>(a.scheduledAt||'9999').localeCompare(b.scheduledAt||'9999'));
  $('content').innerHTML=pageHeader('Your publishing queue','Drafts and plans stay local to this workspace.','<button class="primary" id="queue-create">＋ Create post</button>')+demoBanner()+`<div class="card table-wrap"><table><thead><tr><th>Content</th><th>Platforms & accounts</th><th>Scheduled time</th><th>Status</th><th>Actions</th></tr></thead><tbody>${posts.map(p=>`<tr><td class="post-cell">${esc(p.text.slice(0,100))}${p.media?.length?`<small>${p.media.length} image(s)</small>`:''}</td><td>${esc(postAccounts(p))}</td><td>${dateLabel(p.scheduledAt)}${p.status==='scheduled'&&Date.parse(p.scheduledAt)<Date.now()?'<small>Due · demo only, not sent</small>':''}</td><td>${badge('Demo')}${badge(p.status)}</td><td><div class="table-actions">${['draft','scheduled'].includes(p.status)?`<button class="text-button" data-edit-post="${p.id}">Edit</button><button class="text-button" data-cancel-post="${p.id}">Cancel</button>`:''}<button class="text-button" data-duplicate-post="${p.id}">Duplicate</button></div></td></tr>`).join('')}</tbody></table>${posts.length?'':empty('A fresh start for your content','Create a post and save it as a draft or schedule a demo.')}</div>`;
  $('queue-create').onclick=()=>{composer={text:'',accountIds:[],media:[],status:'draft',scheduledAt:''};navigatePage('composer');};bindPostActions();
}
function bindPostActions(){
  document.querySelectorAll('[data-edit-post]').forEach(b=>b.onclick=()=>{composer=JSON.parse(JSON.stringify(demoStore.data.posts.find(p=>p.id===b.dataset.editPost)));navigatePage('composer');});
  document.querySelectorAll('[data-cancel-post]').forEach(b=>b.onclick=safely(()=>{demoStore.cancelPost(b.dataset.cancelPost);renderScheduler();toast('Post cancelled.');}));
  document.querySelectorAll('[data-duplicate-post]').forEach(b=>b.onclick=()=>{composer=JSON.parse(JSON.stringify(demoStore.data.posts.find(p=>p.id===b.dataset.duplicatePost)));delete composer.id;delete composer.publishedAt;composer.status='draft';composer.scheduledAt='';navigatePage('composer');toast('Copy ready to edit. Save it to keep the draft.');});
}
function dayKey(d){return `${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`;}
function renderCalendar(){
  const first=calendarMode==='month'?new Date(calendarDate.getFullYear(),calendarDate.getMonth(),1):new Date(calendarDate);first.setDate(first.getDate()-((first.getDay()+6)%7));first.setHours(0,0,0,0);
  const days=Array.from({length:calendarMode==='month'?42:7},(_,i)=>{const d=new Date(first);d.setDate(d.getDate()+i);return d;});
  $('content').innerHTML=demoBanner()+`<div class="section-head"><div><h2>${calendarDate.toLocaleDateString([], {month:'long',year:'numeric'})}</h2><p class="muted">${calendarMode==='week'?`${dateLabel(days[0])} – ${dateLabel(days[6])} · `:''}Local time · Click a post to edit</p></div><div class="action-row"><button class="secondary" id="calendar-prev" aria-label="Previous period">←</button><button class="secondary" id="calendar-today">Today</button><button class="secondary" id="calendar-next" aria-label="Next period">→</button><select id="calendar-mode" class="select" aria-label="Calendar view">${options([['month','Month'],['week','Week']],calendarMode)}</select></div></div><div class="calendar-grid">${['Mon','Tue','Wed','Thu','Fri','Sat','Sun'].map(d=>`<div class="calendar-heading">${d}</div>`).join('')}${days.map(d=>`<section class="calendar-day ${d.getMonth()!==calendarDate.getMonth()?'outside':''} ${dayKey(d)===dayKey(new Date())?'today':''}"><strong>${d.getDate()}</strong>${demoStore.data.posts.filter(p=>p.status==='scheduled'&&p.scheduledAt&&dayKey(new Date(p.scheduledAt))===dayKey(d)).map(p=>`<button class="calendar-post" data-edit-post="${p.id}"><strong>${new Date(p.scheduledAt).toLocaleTimeString([], {hour:'numeric',minute:'2-digit'})}</strong><span>${esc(p.text.slice(0,60))}</span><small>${esc(postAccounts(p))}</small><small>Scheduled · Demo</small></button>`).join('')}</section>`).join('')}</div>`;
  $('calendar-prev').onclick=()=>moveCalendar(-1);$('calendar-next').onclick=()=>moveCalendar(1);$('calendar-today').onclick=()=>{calendarDate=new Date();renderCalendar();};$('calendar-mode').onchange=e=>{calendarMode=e.target.value;renderCalendar();};bindPostActions();
}
function moveCalendar(step){if(calendarMode==='month')calendarDate=new Date(calendarDate.getFullYear(),calendarDate.getMonth()+step,1);else calendarDate.setDate(calendarDate.getDate()+step*7);renderCalendar();}
function renderAnalytics(){
  const m=WorkspaceData.metrics(demoStore.data);
  $('content').innerHTML=demoBanner()+stats()+`<div class="overview-grid"><section class="card"><h3>Platform distribution · Real accounts</h3>${distribution()}</section><section class="card"><h3>Demo message overview</h3>${[['Received',m.messages],['Unread',m.unread],['AI lead conversations',m.leads],['Marked replied',demoStore.data.messages.filter(m=>m.leadStatus==='Replied').length],['Marked won',demoStore.data.messages.filter(m=>m.leadStatus==='Won').length]].map(([label,value])=>`<div class="report-row"><span>${label}</span><strong>${value}</strong></div>`).join('')}<p class="muted">Derived from local demo conversations, including your review changes.</p></section><section class="card"><h3>Engagement</h3>${empty('Awaiting official analytics','Reach, impressions and engagement require approved platform APIs.')}</section><section class="card"><h3>Lead categories · Mock AI</h3>${WorkspaceData.categories.map(c=>`<div class="report-row"><span>${esc(c.replaceAll('_',' '))}</span><strong>${demoStore.data.messages.filter(m=>m.classification.category===c).length}</strong></div>`).join('')}</section></div>`;
}
function renderReports(){
  $('content').innerHTML=pageHeader('Workspace reports','Export a clear summary of your local planning activity.')+demoBanner()+`<div class="overview-grid"><section class="card"><span class="badge">AVAILABLE · LOCAL SUMMARY</span><h3>Workspace snapshot</h3><p class="muted">Real account totals alongside explicitly labeled demo message, lead and publishing counts. No cookies, tokens, session identifiers or message content.</p><button class="primary" id="export-report">Download JSON report</button></section><section class="card"><span class="badge">INTEGRATION PENDING</span><h3>Platform performance</h3><p class="muted">Audience growth, engagement and campaign reports need official analytics permissions. No external analytics are connected.</p></section></div>`;
  $('export-report').onclick=safely(()=>{const report={generatedAt:new Date().toISOString(),real:{savedAccounts:appState.accounts.length,platformDistribution:Object.fromEntries(Object.keys(PLATFORMS).map(id=>[id,appState.accounts.filter(a=>a.platform===id).length]))},demo:{...WorkspaceData.metrics(demoStore.data),note:'Simulated messages and publishing; not production analytics'},integrations:'pending'};const url=URL.createObjectURL(new Blob([JSON.stringify(report,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download='social-workspace-report.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);toast('Report download requested.');});
}
function renderListening(){
  const mentions=demoStore.data.messages.filter(m=>demoStore.data.keywords.some(k=>m.message.toLowerCase().includes(k.toLowerCase())));
  $('content').innerHTML=pageHeader('Listen for relevant conversations','Explore keyword matching using the local demo message set.')+demoBanner()+`<section class="card"><h3>Tracked keywords</h3><form id="keyword-form" class="action-row"><input id="keyword-input" class="text-input" placeholder="Add a keyword or brand name" maxlength="80" aria-label="Keyword"><button class="primary">Add keyword</button></form><div class="keyword-list">${demoStore.data.keywords.map((k,i)=>`<button class="keyword" data-remove-keyword="${i}" title="Remove keyword">${esc(k)} ×</button>`).join('')}</div><p class="muted">Demo matching only. No websites are monitored or scraped.</p></section><h3 class="section-title">Demo mentions <span class="count">${mentions.length}</span></h3><div class="card table-wrap"><table><thead><tr><th>Source</th><th>Mention</th><th>Sentiment</th><th>Received</th></tr></thead><tbody>${mentions.map(m=>`<tr><td>${platformIcon(m.platform)} ${esc(PLATFORMS[m.platform]?.name)}<small>${esc(m.senderName)}</small></td><td>${esc(m.message)}</td><td>${badge('Demo')}${badge('Not analyzed')}</td><td>${dateLabel(m.timestamp)}</td></tr>`).join('')}</tbody></table>${mentions.length?'':empty('No demo mentions','Try “website” or “SEO” to match sample messages.')}</div>`;
  $('keyword-form').onsubmit=safely(e=>{e.preventDefault();const keyword=$('keyword-input').value.trim();if(!keyword)return;if(demoStore.data.keywords.some(k=>k.toLowerCase()===keyword.toLowerCase()))return toast('That keyword is already tracked.');demoStore.commit(data=>data.keywords.push(keyword));renderListening();});
  document.querySelectorAll('[data-remove-keyword]').forEach(b=>b.onclick=safely(()=>{demoStore.commit(data=>data.keywords.splice(Number(b.dataset.removeKeyword),1));renderListening();}));
}
